///|
let debug = false

///|
fn main {
  try {
    instructions!()
    // dormann!()
    // lorenz!()
    // nestest!()
    // sidtest!()
  } catch {
    error => println(error)
  }
}
